name: Quarkiverse Perform Release
runName: Perform ${{github.event.inputs.tag || github.ref_name}} Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  attestations: write
  idToken: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancelInProgress: true

jobs:
  performRelease:
    name: Perform Release
    uses: quarkiverse/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}
